#pragma once

#define PACKET_SC_CREATE_MY_PLAYER 0
#define PACKET_SC_CREATE_OTHER_PLAYER 1

#define PACKET_SC_DELETE_MY_PLAYER 2
#define PACKET_SC_DELETE_OTHER_PLAYER 3

#define PACKET_CS_PLAYER_MOVE_START 4
#define PACKET_CS_PLAYER_MOVE_END 5
#define PACKET_SC_PLAYER_MOVE_START 6
#define PACKET_SC_PLAYER_MOVE_END 7

#define MOVE_DIR_LEFT 0
#define MOVE_DIR_UP 1
#define MOVE_DIR_RIGHT 2
#define MOVE_DIR_DOWN 3